### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [Ludovicus-Maior/WoW-Pro-Guides#1104]
Message: [ADDON_ACTION_BLOCKED] AddOn 'WoWPro' tried to call the protected function 'WoWPro.MainFrame:Hide()'.
Time: Thu Oct  8 02:33:23 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'WoWPro' tried to call the protected function 'WoWPro.MainFrame:Hide()'.
Interface\AddOns\WoWPro\WoWPro_Events.lua:500: in function `ZONE_CHANGED_NEW_AREA'
Interface\AddOns\WoWPro\WoWPro_Parser.lua:1017: in function <Interface\AddOns\WoWPro\WoWPro_Parser.lua:979>
[C]: ?
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:73: in function <...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:71>
...\AddOns\Details\Libs\AceBucket-3.0\AceBucket-3.0.lua:89: in function `func'
...\AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...\AngryAssignments\libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals: <none>

**Comment by Blanckaert** [comment]
If you downloaded from github today, the current retail version of WP is listed as BFA.  If you downloaded 'Main' that is the current release for Shadowlands.

**Comment by SegoItCh** [comment]
It's classic version

**Comment by Blanckaert** [comment]
Okay, I wasn't sure, sorry about that.   Can you give some more details
what you were doing at the time it happened?

**Comment by Ludovicus-Maior** [comment]
@SegoItCh Were you in combat and then entered a dungeon when this happend?

**Comment by SegoItCh** [comment]
Maybe

**Comment by elidion** [comment]
Found issue, auto instance hide had no combat check.  Should be resolved in PR:  1108
