### ISSUE TITLE
WoWPro: Malformed profession tag errors

### ISSUE THREAD

**Issue by chroots** [Ludovicus-Maior/WoW-Pro-Guides#1583]
I am getting lot of errors spewed on my logging window at Ashenvale as Horde hunter 21lvl toon. WoW-Pro Version: 1.13.6-E0 (Classic) under Guide ID: Classic-15-21-Hendo-TheBarrens

113618 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113625 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113642 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113649 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113654 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113659 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113708 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113717 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113718 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202 
113737 WoWPro: Malformed profession tag [Lockpicking;633;0+101;1] at step 202

**Comment by Blanckaert** [comment]
Yes, we are aware of the issue with Classic Profession errors.  Unfortunately,  the main author has been a bit under the weather with a medical issue.  We are hoping to have it fixed before our next release.

**Comment by leparduk** [comment]
This issue has started appearing again since yesterday

**Comment by Spoony36** [comment]
Thanks for the report, we will take a look
