### ISSUE TITLE
Guides aren't well scaled ?

### ISSUE THREAD

**Issue by Jenocke** [Ludovicus-Maior/WoW-Pro-Guides#1709]
Guide from hellfire peninsula say min 58 and to 62. Zangarmarsh start at 62, but even as a 60, I wasn't 62 yet. After grinding a little to reach it, I started Zangar, only to finish at 63. I started Terokkar, then switched at 64 to Blade Edge's mountain (guide say 64 min). But right at the start, the guide asks to take a level 65 quest...

Alliance Player at 32.20,92.64/1949@"Blade's Edge Mountains" aka "Blade's Edge Mountains" aka "Blade Tooth Canyon"

Step Info for CLASSIC_BC_Blades_Edge_Mountains:
A Killing the Crawlers¦QID¦10927¦M¦32.2,91.1¦N¦From Sentinel Moonwhisper.¦

**Comment by Blanckaert** [comment]
All the BC guides are based on pre Shadowlands retail...  they are being worked on, unfortunately none of the WoWPro team had beta much before launch.

**Comment by Jenocke** [comment]
I thought so :)
I was just passing the information :)
Oh, I can tell you that "vengeful harbinger" is in fact "vengeful souls"
(or the other way, don't remember) and the objective is kill the harbringer
(not the 5 souls). It works even if someone else already started and the
mob is greyed. You can help and it count
