### ISSUE TITLE
|PVP| tag for use with |O| tag.

### ISSUE THREAD

**Issue by kristjin** [Ludovicus-Maior/WoW-Pro-Guides#188]
Checks if you are on PVP server, or have PVP turned on, to enable display of step.

**Comment by Ludovicus** [comment]
Having pathologically avoided being on PVP servers my entire wow career, I am not sure what quests except quests that flag you for PVP would be tagged by this tag.

That way people who detest PVP quests can flip the switch in their control panel and then they would never see PVP quests.

I know some folks who would use a switch like that.
