### ISSUE TITLE
Frame Location Changing after Turning in / Picking up New Quest

### ISSUE THREAD

**Issue by jtmunn** [Ludovicus-Maior/WoW-Pro-Guides#1979]
Please create a new issue, preferably with some  screenshots or even a short low-res movie demonstrating the issue.  I have to confess, I'm  pretty dense when it comes to UI issues, so pictures and a step-by-step description has alot of value.

_Originally posted by @Ludovicus-Maior in https://github.com/Ludovicus-Maior/WoW-Pro-Guides/issues/443#issuecomment-1101696845_

**Comment by jtmunn** [comment]
This is in TBC: Classic FYI.

1.  Pickup a quest and align frame with something else in UI for reference (top aligned with right action bar):
![2022-04-18 14_40_43-Greenshot](https://user-images.githubusercontent.com/17181361/163870571-e533acf6-0353-48db-b552-24c294d37539.png)

1.  After questing a while, turning in quests and picking up a new quest, the frame is no longer aligned:
![2022-04-18 15_07_32-Greenshot](https://user-images.githubusercontent.com/17181361/163870803-7d80db8f-a3e9-4fe1-8dbb-bcf52fe49f33.png)

1.  My hunch is that the code is incorrectly capturing the origin point (top right) or that the frame is needing extra space after the origin point was set due to the size required for the current quest block (maybe due to quest-use items? since I only noticed after the item appeared for the quest?)

**Comment by Ludovicus-Maior** [comment]
Thanks for the screenshots.  Would you mind uploading a copy of your toons state file?
On my mac, it is located here:  `/Applications/World\ of\ Warcraft/_classic_/WTF/Account/xxx\#1/Mankrik/Teuhcatl/SavedVariables/WowPro.lua` .  I bet you are on windows, but once you find your wow client location and flip the slashes, it is pretty much the same.

**Comment by jtmunn** [comment]
[WoWPro.lua.txt](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/files/8508690/WoWPro.lua.txt)

I had to change to .txt because it said the other file type was not supported.  For what it's worth, this happens on each of my toons.  It's not game breaking, I will continue to use the AddOn, it's just a little frustrating :)

**Comment by Ludovicus-Maior** [comment]
@jtmunn I'm sorry to bother you again, but you gave me the state file for your character, not the global one.
Please look for the `SavedVariables\WoWPro.lua` file that is not under the realm\character directory.

**Comment by jtmunn** [comment]
@Ludovicus-Maior - Sorry, I thought I followed the path you provided.  Here it is:
[WoWPro.lua (2).txt](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/files/8513981/WoWPro.lua.2.txt)

**Comment by jtmunn** [comment]
Is there a way that I can change it to be top right?

**Comment by Ludovicus-Maior** [comment]
Nope!   That's why I need to add some code to let you set this, if you care.
This just let me confirm that it was working as designed, which is not what **you** want.

**Comment by jtmunn** [comment]
I understand.  I really do appreciate your help.  I have some dev experience myself so if there's anything I can do please let me know.  I've never worked with LUA / Wow Addons before, but wouldn't mind getting my hands dirty if it helps out.

**Comment by Ludovicus-Maior** [comment]
Thanks for the offer, but even with Lua experience, the Blizzard UI code is full of nasty pitfalls.
I'll think about it for a few days and try a fix this weekend.   I'll tag you when the the checkins come in.
