### ISSUE TITLE
Wotlk alpha. No leveling guides

### ISSUE THREAD

**Issue by GregoryGH** [Ludovicus-Maior/WoW-Pro-Guides#2053]
Got a wotlk alpha version but dont see any wotlk leveling guides in the guide list

**Comment by Blanckaert** [comment]
Try downloading direct from github, but this is an known issue.  Unfortunately Ludo, does not have beta access and is trying with the help of others to get the addon to work.  Please look through the #beta-ptr-testing channel for more information.    

Currently an issue is Blizz using the same release coding as TBC, so if we get WotLK to work, TBC doesn't work properly.  Another is there is a coding issue with our old WotLK guides that is being fixed too.
