### ISSUE TITLE
DF Zone Data

### ISSUE THREAD

**Issue by Aldarana** [Ludovicus-Maior/WoW-Pro-Guides#2114]
Did a `/run WoWPro.Functionalize(10)` on the beta here are the results:
[DF Zone IDs.txt](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/files/9617648/DF.Zone.IDs.txt)

**Comment by Spoony36** [comment]
Thanks for this, Feel free to join the addons discord server 

https://discord.gg/aarduK7
