### ISSUE TITLE
invalid waypoints  - WotLK Classic

### ISSUE THREAD

**Issue by miguelomp** [Ludovicus-Maior/WoW-Pro-Guides#2130]
WoW WolTK Classic

Valid coordinates (11.44,28.72)

Validate for quests around

NPC that I could saw around

- Augustus the Touched
- Egan

![image](https://user-images.githubusercontent.com/11744486/193356338-b546f36b-8a2e-4c72-b89c-0dbecd3b52e3.png)

**Comment by miguelomp** [comment]
new finding

![image](https://user-images.githubusercontent.com/11744486/193361760-bdc42c59-e455-437f-92f1-d6cf12a75a9d.png)

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193364946-1921e526-33c7-4c65-88a5-b1637f95c581.png)

**Comment by miguelomp** [comment]
I'll keep uploading captures of invalid waypoints from the addon.

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193365381-0b8b239d-2335-4c6c-8f06-9bb2e93d9c2b.png)

**Comment by miguelomp** [comment]
I read somewhere this is due to DK zone integration to the map in the zone. With these capture maybe is possible to calculate some kind of direction and add or subs to all waypoints in this zone?

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193419519-1b104123-5bb1-47a2-ba98-9c3ba87e07bc.png)

quest not available in WolTK Classic. Maybe because it was removed in patch 3.0.8

![image](https://user-images.githubusercontent.com/11744486/193419648-81302d2b-d40f-4da2-9515-2fbac919508a.png)

**Comment by miguelomp** [comment]
> ![image](https://user-images.githubusercontent.com/11744486/193419519-1b104123-5bb1-47a2-ba98-9c3ba87e07bc.png)
> 
> quest not available in WolTK Classic. Maybe because it was removed in patch 3.0.8
> 
> ![image](https://user-images.githubusercontent.com/11744486/193419648-81302d2b-d40f-4da2-9515-2fbac919508a.png)

probably should be replaced by 

![image](https://user-images.githubusercontent.com/11744486/193424656-5ea365a7-8573-4b48-8e3c-7c1392f98ccd.png)

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193430103-62afd341-aa61-46f8-8344-0bf8af8f55a2.png)
wrong coordinates
wrong NPC

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193430148-0c7ccb9c-bbf2-4e89-a0ac-5b49619414b5.png)
wrong coordinates

**Comment by miguelomp** [comment]
![image](https://user-images.githubusercontent.com/11744486/193449576-4ad98a66-1f4c-411e-8c00-b410a4cc4b0c.png)
previous step was pointing to swamp of sorrows

**Comment by Spoony36** [comment]
Please raise these in the addons discord channel 

https://discord.gg/aarduK7

Once there you will see a open-a-ticket channel
