### ISSUE TITLE
DF guide file location

### ISSUE THREAD

**Issue by Aldarana** [Ludovicus-Maior/WoW-Pro-Guides#2139]
The WoWPro_Leveling/Neutral/DF_Waking_Shores.lua file is marked in the meta data as an alliance only guide. Could it please be moved into the Alliance folder rather than being in the Neutral folder?

**Comment by Spoony36** [comment]
As far as I understand the guides will be in the neutral section as the quests are identical for both sides apart from a few lead in quests.

But those lead in quests will work no matter what faction you choose because of the magic behind the scenes which determines if you are horse or alliance
