### ISSUE TITLE
Extra - in line 786 of Wrath Horde Chapter 3

### ISSUE THREAD

**Issue by Jeremy7600** [Ludovicus-Maior/WoW-Pro-Guides#2273]
https://github.com/Ludovicus-Maior/WoW-Pro-Guides/blob/8e7c8324eff5e0b585116e89c22014e08d16e4d4/WoWPro_Leveling/Wrath/Horde/WOTLK_VAN_41_51_HordeChapter3.lua#L786

This line has an extra - in it before 7003, causing an error like this:

544x WoWPro\WoWPro_Broker.lua:1639: attempt to concatenate local 'jqid' (a boolean value)
[string "@WoWPro\WoWPro_Broker.lua"]:1639: in function `NextStep'
[string "@WoWPro\WoWPro_Broker.lua"]:922: in function `RowUpdate'
[string "@WoWPro\WoWPro_Broker.lua"]:1476: in function `rowContentUpdate'
[string "@WoWPro\WoWPro_Broker.lua"]:1507: in function <WoWPro\WoWPro_Broker.lua:1422>
[string "=[C]"]: ?
[string "@WoWPro\Libraries\AceBucket-3.0\AceBucket-3.0-4.lua"]:69: in function <...Ons\WoWPro\Libraries\AceBucket-3.0\AceBucket-3.0.lua:67>
[string "@WoWPro\Libraries\AceBucket-3.0\AceBucket-3.0-4.lua"]:85: in function `func'
[string "@WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0-17.lua"]:57: in function <WeakAuras\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by Spoony36** [comment]
Thanks for the report, surprised it hasn't been mentioned since
Fix is in a pull request so should be fixed soon.

Thanks for the continued support of the addon.
