### ISSUE TITLE
Ohn'ahran Plains error spam

### ISSUE THREAD

**Issue by Veyska** [Ludovicus-Maior/WoW-Pro-Guides#2297]
Steps are not progressing when completed but the guide will jump forward to catch up on a /reloadui.  However, doing basically anything, from quest progression to combat, triggers the following error.  Tried several /reloadui as well as re-installing, no luck.

246x WoWPro/WoWPro_Broker.lua:2619: attempt to index a nil value
[string "@WoWPro/WoWPro_Broker.lua"]:2619: in function `NextStep'
[string "@WoWPro/WoWPro_Broker.lua"]:1476: in function <WoWPro/WoWPro_Broker.lua:1432>
[string "=[C]"]: ?
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:69: in function <Ace3/AceBucket-3.0/AceBucket-3.0.lua:67>
[string "@Ace3/AceBucket-3.0-4/AceBucket-3.0.lua"]:85: in function `func'
[string "@Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

**Comment by Veyska** [comment]
Tried re-enabling once I'd unlocked the Maruuk Centaur faction out of curiosity, no magically fixed guide/addon.  Alas.

**Comment by mgit2022** [comment]
Same error here, hoping for a fix, fantastic addon

**Comment by Veyska** [comment]
Appears to be fixed (at least for me) with WoWPro 2022.11.29.A.  Huzzah!
