### ISSUE TITLE
WoWPro.TrashItem needs updated to the new C_Container functions.

### ISSUE THREAD

**Issue by Grimsbain** [Ludovicus-Maior/WoW-Pro-Guides#2401]
The following functions in WoWPro.TrashItem (WoWPro_Broker.lua) need to be updated to the new C_Container style.
```
C_Container.GetContainerNumSlots(bag)
C_Container.GetContainerItemID(bag,slot)
C_Container.PickupContainerItem(bag,slot)
```

**Comment by Ludovicus-Maior** [comment]
Fixed in https://github.com/Ludovicus-Maior/WoW-Pro-Guides/commit/0bf940204f6eeb901533844a058bf75a79b815cb
@Hendo72 committed on Mar 8
