### ISSUE TITLE
Localization for Chinese players

### ISSUE THREAD

**Issue by sc03209** [Ludovicus-Maior/WoW-Pro-Guides#2418]
I'm a huge fan to Wow and I love leveling with a guide. Since I can read English so it's easy for me to follow the guide but most of my friends can't read. I'm so eager to participate in translating the addon but I don't know where to start. I tried to add a Chinese entry in WoWPro_Localization.lua but it doesn't work.
Please let me know where I can go to and I'm ready for the localization work.
Thanks!

**Comment by Spoony36** [comment]
@Ludovicus-Maior

**Comment by Ludovicus-Maior** [comment]
Good news:  You can help to localize then addon.
Bad news: it it will not help with the guides.

I am willing to help with the addon localization, but I fear the guide localization may be beyond what we can do.

**Comment by sc03209** [comment]
Thanks for your reply. For sure I can start with the addon localization first, but I was thinking that if the addon support to read the quest infos directly from Grail, like Wholly, which will greatly help a lot for localization since it's hard for us to understood the quest name in other language. As long as we have the quest name associated with Grail, which is fully localized in CN, it can be much time-saving to do the leveling guide translation.

I know it could take pretty much time on it but that could help players from all over the world to use the unlocalized addons first.

Hope that will make sense.

**Comment by Ludovicus-Maior** [comment]
@sc03209 Support for localizing the quest names from Grail already exists!  If Grail is installed, we use it to map the text for the A/T steps into the local language.  However, doing that for the step text, for NPC names is much harder; again possible for A/T steps, but near impossible for any other step type.

**Comment by sc03209** [comment]
Understood. It seems that my addon doesn't map the A/T steps of the quest names. When I open a guide, all texts are in EN.

**Comment by Ludovicus-Maior** [comment]
You have Grail installed and the "Grail Quest Lines" enabled in the expert config section enabled and it does not work?  If so, that is a bug.  I do occasionally check that, as my first language is Spanish and not English.

As far as localizing the addon goes, I think there are some tools that will help to both add the lookups though the `L` table and to add entries to the tables in `WoWPro_Localization.lua`  Once that is done, localizing the addon for other languages should be possible.  If I can get it to work for Spanish, then you can do it for Chinese!

**Comment by sc03209** [comment]
Great news. Thank you for letting me know.

Ludovicus Maior ***@***.***>于2023年4月24日 周一01:34写道：

**Comment by Spoony36** [comment]
If you are able to read chinese then does this look about right?

    ["Guide Display"] = "指南显示",
    ["Options that alter the way the guide frame looks"] = "更改指南框架外观的选项",
    ["Options"] = "选项",
    ["Enable Addon"] = "启用插件",
    ["Enable Debug"] = "启用调试",
    ["Enables/Disables debug logging"] = "启用/禁用调试日志",
    ["Auto Select"] = "自动选择",
    ["Enables/Disables automatically selecting quests/flights from NPCs"] = "启用/禁用自动从NPC选择任务/飞行",
    ["Auto Accept"] = "自动接受",
    ["Enables/Disables automatically accepting quests from NPCs"] = "启用/禁用自动接受NPC的任务",
    ["Auto Turnin"] = "自动提交",
    ["Enables/Disables showing the WoW-Pro guide addons."] = "启用/禁用显示WoW-Pro指南插件。",
    ["Enables/Disables automatically turning in quests to NPCs"] = "启用/禁用自动向NPC提交任务",
    ["Enable Pet Battles"] = "启用宠物对战",
    ["Enables/Disables automatic pet battle team selection in some guides"] = "在一些指南中启用/禁用自动宠物对战队伍选择",
    ["Enable Rares"] = "启用稀有",
    ["Enables/Disables killing optional Rares in guides."] = "在指南中启用/禁用杀死可选的稀有。",
    ["Enable Treasures"] = "启用宝藏",
    ["Enables/Disables treasure hunting steps in guides."] = "在指南中启用/禁用寻宝步骤。",
    ["Skip Dungeon Quests"] = "跳过地下城任务",
    ["Skips dungeon-specific quests outside Dungeon guides."] = "在地下城指南之外跳过特定于地下城的任务。",
    ["Skip Flights"] = "跳过飞行",
    ["Skips most flight steps when you have flying in that zone"] = "当你在该区域飞行时，跳过大多数飞行步骤",
    ["Master Addon Tools"] = "主要插件工具",
    ["Reset WoWPro Addons"] = "重置WoWPro插件",
    ["On this page you can edit the way the guide frame looks."] = "在此页面上，您可以编辑指南框架的外观。",
    ["Enable Drag"] = "启用拖动",
    ["Enables the guide window to be moved by clicking anywhere on it and dragging"] = "允许通过单击任何位置并拖动来移动指南窗口",
    ["Padding"] = "填充",
    ["The padding determines how much blank space is left between the guide text and the border of the guide frame."] = "填充确定指南文本和指南框架边框之间留下多少空白空间。",
    ["Spacing"] = "间距",
    ["Spacing determines how much blank space is left between lines in the guide text. "] = "间距确定指南文本中的行之间留下多少空白空间。",
    ["Enable Instance Hide"] = "启用实例隐藏",
    ["Enables/Disables hiding the active module when inside an instance (Dungeon, Arena ...), unless the guide wants you there!"] = "启用/禁用在实例内（地下城，竞技场...）隐藏活动模块，除非指南要求您在那里！",
    ["Enable Instance Notify"] = "启用实例通知",
    ["Enables/Disables notifying when inside an instance (Dungeon, Arena ...), unless the guide wants you there!"] = "启用/禁用在实例内（地下城，竞技场...）通知，除非指南要求您在那里！",
    ["Enable Combat Hide"] = "启用战斗隐藏",
    ["Enables/Disables hiding the active module when you are in combat."] = "启用/禁用在战斗中隐藏活动模块。",
    ["Mouseover Notes"] = "鼠标悬停注释",
    ["Show notes on mouseover instead of always displaying them."] = "鼠标悬停时显示注释，而不是始终显示。",
    ["Minimap Button"] = "小地图按钮",
    ["Show/hide WoW-Pro mini map button."] = "显示/隐藏WoW-Pro小地图按钮。",
    ["Quest Tracking"] = "任务追踪",
    ["Allows tracking of quests in the guide frame"] = "允许在指南框架中追踪任务",
    ["Show Coordinates"] = "显示坐标",
    ["Shows the coordinates in the note text."] = "在注释文本中显示坐标。",
    ["Auto-Load Guide"] = "自动加载指南",
    ["Will automatically load the next guide when you complete one."] = "当您完成一个指南时，将自动加载下一个指南。",
    ["Scroll Mode"] = "滚动模式",
    ["Displays full, scrollable guide in guide frame, instead of need-to-know info."] = "在指南框架中显示完整的可滚动指南，而不是需要知道的信息。",
    ["Step Completed Sound"] = "步骤完成声音",
    ["Sound played when a guide step is completed"] = "完成指南步骤时播放的声音",
    ["Enable Sound"] = "启用声音",
    ["Plays a check-off sound when a guide step is completed."] = "当完成指南步骤时播放一个勾选声音。",
    ["Left Handed"] = "左撇子",
    ["Put Use and Target Icons on the right side of the guide window."] = "将使用和目标图标放在指南窗口的右侧。",
    ["Resize Settings"] = "调整大小设置",
    ["Resize Handle"] = "调整大小手柄",
    ["Addon Enable and Debugging"] = "插件启用和调试",
    ["Automation"] = "自动化",
    ["Guide Modifiers"] = "指南修饰符",
    ["Guide Selection"] = "指南选择",
    ["Current Guide"] = "当前指南",
    ["Ranks"] = "等级",
    ["Actions"] = "动作",
    ["Expert"] = "专家",
    ["Master-Addon-Tools"] = "主要插件工具",
    ["Enables the guide window to be resized using the resize handle in the lower right corner. \nTurns off auto resizing."] = "启用指南窗口通过右下角的调整大小手柄调整大小。\n关闭自动调整大小。",
    ["Auto Resize"] = "自动调整大小",
    ["Guide will automatically resize to the set number of steps. \nManual resize recommended for advanced users only. \nHides drag handle."] = "指南将自动调整大小到设置的步数。\n仅建议高级用户手动调整大小。\n隐藏拖动手柄。",
    ["Auto Resize: Number of Steps"] = "自动调整大小: 步数",
    ["Number of steps displayed in the guide window. \nThe window is automatically resized to show this number of steps. \nDoes not include sticky steps."] = "指南窗口中显示的步数。\n窗口将自动调整大小以显示这些步数。\n不包括粘性步骤。",
    ["Min Resize - Horiz"] = "最小调整大小 - 水平",
    ["Minimum horizontal pixel size the guide window can be set to."] = "指南窗口可以设置的最小水平像素大小。",
    ["Min Resize - Vert"] = "最小调整大小 - 垂直",
    ["Minimum vertical pixel size the guide window can be set to."] = "指南窗口可以设置的最小垂直像素大小。",
    ["Title Bar"] = "标题栏",
    ["About WoW-Pro"] = "关于WoW-Pro",
    ["WoW-Pro is a addon collection by gamers, for gamers. The collection includes hundreds of free guides covering every facet of World of Warcraft."] ="WoW-Pro是玩家制作的插件集合。该集合包括数百个免费指南，涵盖了《魔兽世界》的各个方面。",
    ["The WoW-Pro addon has brought many of the guides we've built as a community into the game and built on them since WotLK to the Classic(s) and Dragonflight.\n\nDrop by on Discord and say hello"] = "WoW-Pro插件已经将我们作为社区制作的许多指南带入了游戏，并从WotLK到经典版和龙之飞行中对它们进行了改进。\n\n在Discord上打个招呼",
    ["Over the years WoW-Pro has grown into a huge, active community of gamers."] = "多年来，WoW-Pro已经发展成为一个庞大、活跃的玩家社区。",
    ["Enable Title Bar"] = "启用标题栏",
    ["Enables/disables the title bar attached to the guide window."] = "启用/禁用附加到指南窗口的标题栏。",
    ["Title Bar Color"] = "标题栏颜色",
    ["Background color for the title bar."] = "标题栏的背景颜色。",
    ["Backgrounds"] = "背景",
    ["Guide Window Background"] = "指南窗口背景",
    ["Texture used for the guide window background."] = "用于指南窗口背景的纹理。",
    ["Guide Window Color"] = "指南窗口颜色",
    ["Background color for the guide window"] = "指南窗口的背景颜色",
    ["Border Texture"] = "边框纹理",
    ["Texture used for the guide window border."] = "用于指南窗口边框的纹理。",
    ["Enable Border"] = "启用边框",
    ["Enables/disables the border around the guide window."] = "启用/禁用指南窗口周围的边框。",
    ["Sticky Background"] = "粘性背景",
    ["Texture used for sticky step background."] = "用于粘性步骤背景的纹理。",
    ["Sticky Step Color"] = "粘性步骤颜色",
    ["Background color for the sticky step frames."] = "粘性步骤框架的背景颜色。",
    ["Text Formatting"] = "文本格式",
    ["Step Font"] = "步骤字体",
    ["Font used for the main step text."] = "用于主要步骤文本的字体。",
    ["Step Text Size"] = "步骤文本大小",
    ["Size of the main step text."] = "主要步骤文本的大小。",
    ["Step Text Color"] = "步骤文本颜色",
    ["Color of the main step text."] = "主要步骤文本的颜色。",
    ["Note Font"] = "注释字体",
    ["Font used for the note text."] = "用于注释文本的字体。",
    ["Note Text Size"] = "注释文本大小",
    ["Size of the note text."] = "注释文本的大小。",
    ["Note Text Color"] = "注释文本颜色",
    ["Color of the note text."] = "注释文本的颜色。",
    ["Tracker Font"] = "追踪器字体",
    ["Font used for the tracking text."] = "用于追踪文本的字体。",
    ["Tracker Text Size"] = "追踪文本大小",
    ["Size of the tracking text."] = "追踪文本的大小",
    ["Tracker Text Color"] = "追踪文本颜色",
    ["Color of the tracking text."] = "追踪文本的颜色。",
    ["Title Bar Font"] = "标题栏字体",
    ["Font used on the title bar."] = "用于标题栏的字体。",
    ["Title Bar Text Size"] = "标题栏文本大小",
    ["Size of the title bar text."] = "标题栏文本的大小。",
    ["Title Bar Text Color"] = "标题栏文本颜色",
    ["Color of the title bar text."] = "标题栏文本的颜色。",
    ["'As you go:' Font"] = "'随着你的行动:' 字体",
    ["Font used on the top of the sticky frame."] = "用于粘性框架顶部的字体。",
    ["'As you go:' Text Size"] = "'随着你的行动:' 文本大小",
    ["Size of the text on the top of the sticky frame."] = "粘性框架顶部文本的大小",
    ["'As you go:' Text Color"] = "'随着你的行动:' 文本颜色",
    ["Color of the text on the top of the sticky frame."] = "粘性框架顶部文本的颜色。",
    ["Main"] = "主要",
    ["Version"] = "版本",
    ["Addon Version Installed"] = "安装的插件版本",
    ["If a WoWPro addon is behaving oddly, this wipes all saved state across all characters."] = "如果WoWPro插件表现异常，这将清除所有角色的所有保存状态。",
    ["Clear the log"] = "清除日志",
    ["Wow-Pro's Debug Log"] = "Wow-Pro的调试日志",
    ["Show the log"] = "显示日志",
    ["Wow-Pro's Secret Debug Log"] = "Wow-Pro的秘密调试日志",
    ["The WoW-Pro addon has brought many of the guides we've built as a community into the game, and built on them since WotLK to the Classic(s) and Dragonflight."] = "WoW-Pro插件已经将我们作为社区制作的许多指南带入了游戏，并从WotLK到经典版和龙之飞行中对它们进行了改进。",
    ["Drop by on Discord and say hello!"] = "在Discord上打个招呼！",
    ["Discord"] = "Discord",
    ["Quest Engine Delay"] = "任务引擎延迟",
    ["The amount of time to wait for the WoW client to update it's state."] = "等待WoW客户端更新其状态的时间。",
    ["Stay away from the below settings unless you are a developer"] = "除非您是开发人员，否则请远离以下设置",
    ["Debug Classes"] = "调试类",
    ["Enables/Disables loading of all class guides"] = "启用/禁用加载所有职业指南",
    ["Grail Quest Lines"] = "Grail任务线",
    ["Enables/Disables Grail Quest Line Integration"] = "启用/禁用Grail任务线集成",
    ["Grail Check PRE"] = "Grail检查PRE",
    ["Enables/Disables Grail Quest Prerequistite Quest Checking"] = "启用/禁用Grail任务先决任务检查",
    ["Grail Check LEAD"] = "Grail检查LEAD",
    ["Enables/Disables Grail Quest Breadcrumb Quest Checking"] = "启用/禁用Grail任务面包屑任务检查",
    ["Grail Quest Name Check"] = "Grail任务名称检查",
    ["Enables/Disables Grail Quest Quest Name Checking"] = "启用/禁用Grail任务任务名称检查",
    ["Grail Quest Level Check"] = "Grail任务等级检查",
    ["Enables/Disables Grail Quest Quest Level Checking"] = "启用/禁用Grail任务任务等级检查",
    ["Grail Obsolete Quest Check"] = "Grail任务过时检查",
    ["Enables/Disables Grail Quest Quest Obsolete Checking"] = "启用/禁用Grail任务任务过时检查",
    ["Guide Errors Checker"] = "指南错误检查器",
    ["Rank Settings"] = "等级设置",
    ["Global Rank (Difficulty/Completeness)"] = "全局等级（难度/完整性）",
    ["Governs how many steps will be skipped. Use 3 for the most completeness, 1 to skip all non-essential steps."] = "决定跳过多少步骤。使用3可以获得最完整性，使用1可以跳过所有非必要步骤。",
    ["Toon Rank (Difficulty/Completeness)"] = "角色等级（难度/完整性）",

**Comment by Ludovicus-Maior** [comment]
This is wonderful!

**Comment by sc03209** [comment]
It looks okay for me.

**Comment by Ludovicus-Maior** [comment]
@Spoony36 Can this be changed into a PR?
