### ISSUE TITLE
No Guide List / Current Guide

### ISSUE THREAD

**Issue by akrieger-berlin** [Ludovicus-Maior/WoW-Pro-Guides#2489]
Hi,

when i do a right click on the title bar of the wow-pro window and choose Guide List or Current Guide I'm redirected to the options window of wow. There is right now no way to choose guides look into the current guide.

It worked before the PDK Patch. Deactivating all addons (just wow-pro and tomtom is active) don't fix the issue.

The only LUA error I get from BugSack is:

650x DataStore_Quests/DataStore_Quests.lua:232: attempt to call global 'GetNumQuestLogRewardSpells' (a nil value)
[string "@DataStore_Quests/DataStore_Quests.lua"]:232: in function <DataStore_Quests/DataStore_Quests.lua:229>
[string "@DataStore_Quests/DataStore_Quests.lua"]:310: in function <DataStore_Quests/DataStore_Quests.lua:246>
[string "@DataStore_Quests/DataStore_Quests.lua"]:330: in function <DataStore_Quests/DataStore_Quests.lua:329>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
rewards = <table> {
}
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumQuestLogRewardSpells' (a nil value)"

But doesn't look for me it has something to do with this.

**Comment by Spoony36** [comment]
Did i respond to you in Discord on a ticket?

If not discord is the fastest place to get a response but try this

![image](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/assets/6922184/218c448b-29ca-4bd4-8a5e-06fcbc99f247)

**Comment by akrieger-berlin** [comment]
Hi,

thanks for the response. Yes, this way works fine. I completely forgot to try it this way.

And no, this wasn't me on Discord. I have tried the invitation link (https://discord.gg/aarduK7) but only get the message that it cannot be accepted.

**Comment by Spoony36** [comment]
Strange, the discord link works for me.

Can you post the message you are getting when clicking the link? that way we can try to resolve if needed
