### ISSUE TITLE
New bug on auto quest accept

### ISSUE THREAD

**Issue by solitha** [Ludovicus-Maior/WoW-Pro-Guides#2535]
This just started today. Not every time, but often enough to be really annoying across a leveling session.

`2x [ADDON_ACTION_FORBIDDEN] AddOn 'WoWPro' tried to call the protected function 'AcceptQuest()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `AcceptQuest'
[string "@WoWPro/WoWPro_Events.lua"]:1007: in function `QUEST_DETAIL_PUNTED'
[string "@WoWPro/WoWPro_Events.lua"]:971: in function <WoWPro/WoWPro_Events.lua:970>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
`

**Comment by Spoony36** [comment]
Looks like a taint to me and blaming wowpro. In bugsack always click current session tab and keep selecting previous till you cant go no more, then post that error because any after that will almost certainly be a taint and the real culprit is the very first bug listed

![image](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/assets/6922184/56683c33-3528-4ff7-8f2c-787324f5e437)

**Comment by solitha** [comment]
If I understand taint correctly, there's a UI bug and it just blames the next addon it sees. However, I've had few if any bugs with auto-accept turned off.

Nonetheless I'll turn it back on and see if I can relay what you're asking for.

**Comment by solitha** [comment]
Yup. Confirmed it fires as a stand-alone bug.

![image](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/assets/14163320/9ae54b01-17a7-4d78-ab9c-882f23dbe00c)

**Comment by solitha** [comment]
I finally realized this addon got updated somewhere in the blitz. It seems to be working great! Thank you for the fix!
