### ISSUE TITLE
Old Style Guidelist

### ISSUE THREAD

**Issue by Fokusrite** [Ludovicus-Maior/WoW-Pro-Guides#2700]
Hi. Since the change from the listed guides into the new right-click simplistic guide picker, I thought it was over but I was wrong! This newest version of the addon is great since it brings back the list of the guides where, once again, I can sort the guides by name, etc. So this is great news! However, When I right-click on the addon title bar, and then when I click on Old Style Guidelist, in that window there's no Leveling tab. There's every tab except the single most important one which is the Leveling tab. I don't know why it's missing but i thought you shuold know it's missing.

**Comment by Spoony36** [comment]
Hi. This will return in the next update hopefully, Blizz has deprecated some frames and the old style guidelist is one of them, We have put it back in until Blizz breaks it permanently then it will probably only be the new style available

**Comment by Fokusrite** [comment]
thanks.
