### ISSUE TITLE
multiple lua notices, world events - wrath classic

### ISSUE THREAD

**Issue by amey1956** [Ludovicus-Maior/WoW-Pro-Guides#2721]
8x Interface_Wrath\FrameXML\Bindings.xml:14 Couldn't open WoWPro_WorldEvents/Wrath/Alliance/Guides.xml

8x Interface_Wrath\FrameXML\Bindings.xml:16 Couldn't open WoWPro_WorldEvents/Wrath/Horde/Guides.xml

8x Interface_Wrath\FrameXML\Bindings.xml:1 Interface_Wrath\FrameXML\Bindings.xml:14 Couldn't open WoWPro_WorldEvents/Wrath/Alliance/Guides.xml

8x Interface_Wrath\FrameXML\Bindings.xml:1 Interface_Wrath\FrameXML\Bindings.xml:16 Couldn't open WoWPro_WorldEvents/Wrath/Horde/Guides.xml

**Comment by amey1956** [comment]
using ## Version: 2024.03.20.A for wrath classic

**Comment by Spoony36** [comment]
Should be fixed in next release, thanks for the heads up and discord is the fastest way to report issues if you use that.

**Comment by Hendo72** [comment]
Thank you for your report. The team has corrected the issue and will be in the next release.
