### ISSUE TITLE
Multiple errors in Cata pre-patch

### ISSUE THREAD

**Issue by Gemini1661** [Ludovicus-Maior/WoW-Pro-Guides#2735]
Several errors generated at login.

> 27x WoWPro_Leveling/WoWPro_Leveling_GuideList.lua:105: attempt to index local 'guide' (a string value)
> [string "@WoWPro_Leveling/WoWPro_Leveling_GuideList.lua"]:105: in function <WoWPro_Leveling/WoWPro_Leveling_GuideList.lua:102>
> [string "@WoWPro_Leveling/WoWPro_Leveling_GuideList.lua"]:240: in function `RegisterGuide'
> [string "@WoWPro_Leveling/Classic_Cata/Alliance/01_05_Gylin_Dwarf_Starter.lua"]:223: in main chunk
> 
> Locals:
> guide = "GylDwa0105"
> (*temporary) = "0 - 0"
> (*temporary) = "%d - %d"
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "0 - 0"
> (*temporary) = "attempt to index local 'guide' (a string value)"
> rangeFormat = "%d - %d"
> LevelRefresh = <function> defined @WoWPro_Leveling/WoWPro_Leveling_GuideList.lua:81
> GetGuideContent = <function> defined @WoWPro_Leveling/WoWPro_Leveling_GuideList.lua:48
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Neutral/Guides.xml:15 Error loading WoWPro_Leveling/86_88_Emmaleah_Valley4Winds.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Neutral/Guides.xml:16 Error loading WoWPro_Leveling/88_89_Emmaleah_KunLaiSummit.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Neutral/Guides.xml:17 Error loading WoWPro_Leveling/89_90_Emmaleah_Dread_Wastes.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Neutral/Guides.xml:18 Error loading WoWPro_Leveling/89_90_Emmaleah_Townlong_Steppes.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Horde/Guides.xml:47 Error loading WoWPro_Leveling/85_86_Emmaleah_JadeForest.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 3x WoWPro_Leveling/Classic_Cata/Horde/Guides.xml:48 Error loading WoWPro_Leveling/87_88_Emmaleah_KrasarangWilds.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 5x WoWPro_Leveling/Classic_Cata/Alliance/Guides.xml:48 Error loading WoWPro_Leveling/85_86_Rajitazi_JadeForest.lua
> 
> -----------------------------------------------------------------------------------------------------------------------------
> 
> 4x WoWPro_Leveling/Classic_Cata/Alliance/Guides.xml:49 Error loading WoWPro_Leveling/87_88_Rajitazi_KrasarangWilds.lua

**Comment by Spoony36** [comment]
Should be fixed with Latest release.

Thanks for the Report!
