### ISSUE TITLE
Missing Cata Durotar

### ISSUE THREAD

**Issue by Drecondius** [Ludovicus-Maior/WoW-Pro-Guides#2741]
You can't be any more simple, the mod is missing the CATA_Durotar guide for Cata Classic. If the workaround is to pull it from the retail mod, I'll do that but I figured I'd say something as you have troll and orc starting quests, but nothing but azshara next and you can't go there at 5 and survive iirc.

**Comment by Spoony36** [comment]
Fixed for next release
