### ISSUE TITLE
Bad Human warrior guide

### ISSUE THREAD

**Issue by Shyrrenmuo** [Ludovicus-Maior/WoW-Pro-Guides#2768]
Your guide for human warriors says pick up the the lost rune quest. That quest is not available to human warriors.

**Comment by Blanckaert** [comment]
Classic or retail....  need a bit more info to trace the issue.

**Comment by Blanckaert** [comment]
![Screenshot_20240525_150320_Chrome](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/assets/21347588/04282457-91ca-433d-afb5-7bb945ea227a)


From wowhead, classic

**Comment by Spoony36** [comment]
you can

![image](https://github.com/Ludovicus-Maior/WoW-Pro-Guides/assets/6922184/5b3025d3-0a3c-4190-b863-b275593a0bbb)

**Comment by Shyrrenmuo** [comment]
I am playing classic era, I tried going back multiple lvls and clicking on
him never poped up

**Comment by Cagomei** [comment]
This is a SoD quest. We are not going to make seperate guides for a temporary season, Just ignore rune quests.

**Comment by Hendo72** [comment]
`A The Lost Rune|AVAILABLE|77616|M|50.21,42.22|N|From Llane Beshere.|C|Warrior|R|Human|RUNE|`

The step is in the guide and it's configured to work properly. Could possibly add a LVL|2| tag, but it's not required at that point in the guide.

This is not an issue and can be closed.
