### ISSUE TITLE
Multiple waypoint steps for 1 objective ie 1/4 npcs healed.. 2/4 npcs healed that are all static locations?

### ISSUE THREAD

**Issue by daibosu** [Ludovicus-Maior/WoW-Pro-Guides#2827]
I've been spending hours scouring the internet, and resources.. is there anyway to have a quest complete partial objectives, when the objective is one objective?

For example, the quest is to go heal 4 staticly placed NPC's.

I want to run to the first NPC, click them, 1/4 healed.

Then the guide I am making then tells me to run to the 2nd NPC, click them, 2/4 healed.

Right now it seems like it only has a waypoint for the final NPC, which is confusing for players.

Is there some syntax or something I am missing to help fix that?

**Comment by Cagomei** [comment]
the best thing to do with this kind of situation is to use |QO|1<1| replace the first # with the correct QO and the second # the step number for the quest. if you have 4 doods to heal the second one will be QO|1<2|.

ex. ```C Stone Tracing|QID|82969|M|53.66,60.90|Z|2214;The Ringing Deeps|QO|1<1|NC|N|Golem location triangulated.|EAB|
C Stone Tracing|QID|82969|M|52.69,53.34|Z|2214;The Ringing Deeps|QO|1<2|NC|N|Golem location triangulated.|EAB|
C Stone Tracing|QID|82969|M|51.06,47.19|Z|2214;The Ringing Deeps|QO|1<3|NC|N|Golem location triangulated.|EAB|```

**Comment by daibosu** [comment]
Sick! That is what I was trying to figure out, haven't tested it yet. But that sounds like it is what I needed! Didn't see that in the documentation (or I am just blind!). Thank you.
