### ISSUE TITLE
TWW Waypoints

### ISSUE THREAD

**Issue by zarraydra** [Ludovicus-Maior/WoW-Pro-Guides#2837]
multiple waypoint locations are now incorrect since launch of early access . please double check them and correct . thanks

**Comment by zarraydra** [comment]
the war within guide. so far the quests in the isle of dorn

________________________________

**Comment by Spoony36** [comment]
Check you are on the release from yesterday

![image](https://github.com/user-attachments/assets/1660dc87-6939-497c-adc8-2bd18762c760)

**Comment by Spoony36** [comment]
https://discord.gg/aarduK7 if you are unaware of it but thanks for the report regardless.

As explained, the guides are being updated daily and should be improved in next release

**Comment by zarraydra** [comment]
thanks i will join the discord as i did not know about it
________________________________
