### ISSUE TITLE
Main Campaign quest guide

### ISSUE THREAD

**Issue by Kezz77** [Ludovicus-Maior/WoW-Pro-Guides#2862]
hey
is it possible to make a guide that primarily follows the main story in TWW.

**Comment by Furydins** [comment]
You can get this by setting the guide to rank 1

Right click title bar->Main Settings->Ranks->Set sliders to 1.

Rank 1: Main Storyline
Rank 2: Main Story and most sidequests
Rank 3: Also include group/dungeon quests.
