### ISSUE TITLE
Some bug while loading addon in wow classic sod

### ISSUE THREAD

**Issue by amaxcz** [Ludovicus-Maior/WoW-Pro-Guides#2868]
`1x WoWPro/WoWPro.lua:1449: 'for' limit must be a number
[string "@WoWPro/WoWPro.lua"]:1449: in function `AchievementsScrape'
[string "@WoWPro_Achievements/WoWPro_Achievements_GuideList.lua"]:51: in function <...oWPro_Achievements/WoWPro_Achievements_GuideList.lua:48>
[string "@WoWPro_Achievements/WoWPro_Achievements_GuideList.lua"]:108: in function `GetGuideListInfo'
[string "@WoWPro/WoWPro_GuideList.lua"]:71: in function `SelectTab'
[string "@WoWPro/WoWPro_GuideList.lua"]:18: in function `SetDisplay'
[string "@WoWPro/WoWPro_Templates.lua"]:57: in function <WoWPro/WoWPro_Templates.lua:51>
[string "=[C]"]: in function `Show'
[string "@WoWPro/WoWPro_Config.lua"]:1202: in function `OnAcquire'
[string "@Attune/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:156: in function `Create'
[string "@Recount/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:1091: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1088>
[string "@Recount/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:1179: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1113>
[string "@Recount/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:1642: in function `FeedGroup'
[string "@Recount/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-87/AceConfigDialog-3.0.lua"]:1567: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1551>
[string "=[C]"]: ?
[string "@Attune/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <Attune/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Attune/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Attune/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Attune/Libs/AceGUI-3.0-41/widgets/AceGUIContainer-TabGroup.lua"]:200: in function <...Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua:197>

Locals:
categories = <table> {
 1 = 14808
 2 = 15425
 3 = 168
 4 = 15228
 5 = 81
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 168 = <table> {
 }
 15228 = <table> {
 }
 15425 = <table> {
 }
 81 = <table> {
 }
 14808 = <table> {
 }
}
(for control) = 168
cid = 168
cinfo = <table> {
}
numItems = nil
(for index) = 1
(for limit) = nil
(for step) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "'for' limit must be a number"`

**Comment by Hendo72** [comment]
I'm not seeing any issue with this and the code hasn't changed in 5 years.
