### ISSUE TITLE
[WoWPro 2024.09.25.C] Horde Part 3 (132/619) - Stranglethorn Fever

### ISSUE THREAD

**Issue by kman3107** [Ludovicus-Maior/WoW-Pro-Guides#2880]
In WoW Classic, at part Horde Part 3 (132/619), it says that Stranglethorn Fever (a repeatable quest) needs 1 Gorilla Fang.
In fact, this quest needs 10 Gorilla Fangs, see attached picture.
![STV-Fever](https://github.com/user-attachments/assets/ff5fd815-4a53-44cc-b03d-501ccdd4a114)

Addon: WoWPro 2024.09.25.C
WoW Client: 1.15.4.56817

Do with this info as you see fit. At least I said something :)

Thanks for an awesome addon. Now I can REALLY relax when playing WoW 👍

**Comment by Spoony36** [comment]
Thank you for this report, i will make the authors aware

**Comment by Hendo72** [comment]
It was reduced to 1 in TBC. I will update the guide accordingly.
