### ISSUE TITLE
Option to adjust x,y offset for use item buttons

### ISSUE THREAD

**Issue by kristjin** [Ludovicus-Maior/WoW-Pro-Guides#63]
The button just feels a little far out to the left to me.  I wanna drag it in, and possibly down a little.  x,y sliders for the use-item button spacing offsets would be delightful.

**Comment by Dissectional** [comment]
Bump? Would really like the ability to move the button to the right side of the frame as I anchor the WoW-Pro frame on the left of my screen.

Any way I can hack this in myself?
