### ISSUE TITLE
Quests Update

### ISSUE THREAD

**Issue by Maddynn** [Ludovicus-Maior/WoW-Pro-Guides#848]
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 27---05 58 21 36" src="https://user-images.githubusercontent.com/68032865/86995112-2ccaa080-c176-11ea-982e-c0c58156c1e4.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 27---16 37 16 86" src="https://user-images.githubusercontent.com/68032865/86995115-2e946400-c176-11ea-9588-9b2d3193d8df.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 27---16 37 56 36" src="https://user-images.githubusercontent.com/68032865/86995117-2fc59100-c176-11ea-9b78-170ba6792c0a.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 27---19 37 23 49" src="https://user-images.githubusercontent.com/68032865/86995118-305e2780-c176-11ea-9a45-b17dd93c3cb9.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 27---19 37 56 57" src="https://user-images.githubusercontent.com/68032865/86995122-3227eb00-c176-11ea-9c2b-ee4bbdaa0dac.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 07 04---23 36 54 66" src="https://user-images.githubusercontent.com/68032865/86995128-33f1ae80-c176-11ea-8dfa-779ec90788f2.png">
![World Of Warcraft - Retail Screenshot 2020 06 02 - 20 10 26 69-min](https://user-images.githubusercontent.com/68032865/86995134-3522db80-c176-11ea-99d8-1834f7790b13.png)
![World Of Warcraft - Retail Screenshot 2020 06 02 - 20 10 34 42-min](https://user-images.githubusercontent.com/68032865/86995136-36ec9f00-c176-11ea-80a9-d72174401690.png)
![World Of Warcraft - Retail Screenshot 2020 06 03 - 23 12 12 53-min](https://user-images.githubusercontent.com/68032865/86995138-381dcc00-c176-11ea-8154-338d255a1e09.png)
![World Of Warcraft - Retail Screenshot 2020 06 03 - 23 12 21 73-min](https://user-images.githubusercontent.com/68032865/86995140-39e78f80-c176-11ea-889d-21ac88639732.png)
![World Of Warcraft - Retail Screenshot 2020 06 03 - 23 55 51 40-min](https://user-images.githubusercontent.com/68032865/86995142-3b18bc80-c176-11ea-9533-8d1eaedf64e6.png)
![World Of Warcraft - Retail Screenshot 2020 06 04 - 17 46 15 06-min](https://user-images.githubusercontent.com/68032865/86995143-3ce28000-c176-11ea-9701-7dd8b8f3ca05.png)
![World Of Warcraft - Retail Screenshot 2020 06 04 - 17 46 23 93-min](https://user-images.githubusercontent.com/68032865/86995146-3eac4380-c176-11ea-85ba-a2723f94fc8a.png)
![World Of Warcraft - Retail Screenshot 2020 06 04 - 18 12 29 81-min](https://user-images.githubusercontent.com/68032865/86995149-40760700-c176-11ea-961a-723fae9d935f.png)
![World Of Warcraft - Retail Screenshot 2020 06 04 - 18 12 45 78-min](https://user-images.githubusercontent.com/68032865/86995151-41a73400-c176-11ea-8691-4a81856b34cd.png)
![World Of Warcraft - Retail Screenshot 2020 06 05 - 23 10 53 13-min](https://user-images.githubusercontent.com/68032865/86995154-4370f780-c176-11ea-8b6f-131c5ee191d2.png)
![World Of Warcraft - Retail Screenshot 2020 06 15 - 17 42 22 04-min](https://user-images.githubusercontent.com/68032865/86995158-44a22480-c176-11ea-885f-02f9af76cf36.png)
![World Of Warcraft - Retail Screenshot 2020 06 15 - 17 42 33 60-min](https://user-images.githubusercontent.com/68032865/86995160-466be800-c176-11ea-9b26-c4c87fb91d3b.png)
![World Of Warcraft - Retail Screenshot 2020 06 15 - 17 47 43 74-min](https://user-images.githubusercontent.com/68032865/86995165-4835ab80-c176-11ea-9606-5319ec5b16e7.png)
![World Of Warcraft - Retail Screenshot 2020 06 15 - 17 48 38 19-min](https://user-images.githubusercontent.com/68032865/86995171-49ff6f00-c176-11ea-91de-1dcf576722ca.png)
![World Of Warcraft - Retail Screenshot 2020 06 15 - 23 34 10 04-min](https://user-images.githubusercontent.com/68032865/86995175-4bc93280-c176-11ea-994d-79d175d5ca2a.png)
![World Of Warcraft - Retail Screenshot 2020 06 16 - 18 49 13 37-min](https://user-images.githubusercontent.com/68032865/86995179-4d92f600-c176-11ea-8f9a-8f1a33cba0e1.png)
![World Of Warcraft - Retail Screenshot 2020 06 16 - 18 49 22 18-min](https://user-images.githubusercontent.com/68032865/86995182-4f5cb980-c176-11ea-8110-d46bd5de6fc4.png)
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 16---22 30 07 99" src="https://user-images.githubusercontent.com/68032865/86995184-51267d00-c176-11ea-9bc7-b379fe62c03c.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 17---23 47 49 96" src="https://user-images.githubusercontent.com/68032865/86995187-5257aa00-c176-11ea-8f45-34f28418cac5.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 17---23 55 11 40" src="https://user-images.githubusercontent.com/68032865/86995189-5388d700-c176-11ea-82e7-da36b23cab6e.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 17---23 59 15 23" src="https://user-images.githubusercontent.com/68032865/86995192-55529a80-c176-11ea-9acd-6d52b0b7fbfd.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 21---00 02 18 02" src="https://user-images.githubusercontent.com/68032865/86995197-5683c780-c176-11ea-874e-5aaf95fb202a.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 21---00 04 03 82" src="https://user-images.githubusercontent.com/68032865/86995198-584d8b00-c176-11ea-83ff-588f667a91e0.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 21---00 05 16 03" src="https://user-images.githubusercontent.com/68032865/86995201-5a174e80-c176-11ea-99bc-cbd95f007132.png">
<img width="1920" alt="world-of-warcraft---retail-screenshot-2020_optimized 06 21---00 05 24 84" src="https://user-images.githubusercontent.com/68032865/86995203-5be11200-c176-11ea-9e91-0257a44e4a25.png">

**Comment by Ludovicus-Maior** [comment]
I'm sorry, is this a bug report for **WoW-Pro** or **Quest Completist** ?
What is the bug?

**Comment by Maddynn** [comment]
> I'm sorry, is this a bug report for **WoW-Pro** or **Quest Completist** ?
> What is the bug?

I'm sorry! Mixed them up

**Comment by Ludovicus-Maior** [comment]
No problem.  I'm sure the other author(s) will appreciate the report!
