### ISSUE TITLE
Got this weird Lua Error Message

### ISSUE THREAD

**Issue by ETERNALTIGGRAIN** [Ludovicus-Maior/WoW-Pro-Guides#953]
So I'm on Game at 2:07 a.m. and for some reason I start getting this Error message when I'm trying to skin, or herb on my rogue. Not sure why since I just got there professions. I reloaded and it popped up again. Here's the error message.

Message: Interface\AddOns\WoWPro\WoWPro_Trade.lua:312: attempt to index local 'trade' (a number value)
Time: Thu Aug 13 02:02:29 2020
Count: 1
Stack: Interface\AddOns\WoWPro\WoWPro_Trade.lua:312: attempt to index local 'trade' (a number value)
[C]: ?
Interface\AddOns\WoWPro\WoWPro_Trade.lua:312: in function `UpdateTradeSkillsTable'
Interface\AddOns\WoWPro\WoWPro_Trade.lua:247: in function `UpdateTradeSkills'
Interface\AddOns\WoWPro\WoWPro_Events.lua:469: in function `?'
Interface\AddOns\WoWPro\WoWPro_Events.lua:1006: in function <Interface\AddOns\WoWPro\WoWPro_Events.lua:995>

**Comment by Ludovicus-Maior** [comment]
Sorry for the delay.  This is fixed in version B4 of the addon.

**Comment by Ludovicus-Maior** [comment]
6bbe60cbeda5a4919b9037b9365564760ad94103
